version: '3.8'

services:
  my-python-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /codesys/NextoUser/Files/docker/var-lib/:/app
    container_name: mypythoncontainer